- name: Setup offline sources on asset host
  hosts: assethost
  become: yes
  tasks:
  - file:
      path: /opt/assets
      state: directory

  - name: Copy helm containers
    unarchive:
      src: "/home/{{ ansible_user }}/wire-server-deploy/containers-helm.tar"
      dest: /opt/assets
      remote_src: yes

  - name: Create serve-assets systemd service
    copy:
      src: ../files/serve-assets.service
      dest: /etc/systemd/system/serve-assets.service

  - name: Setup serve-assets systemd service
    systemd:
      name: serve-assets
      state: restarted
      enabled: yes
      daemon-reload: yes
    