- name: Install Helm charts
  hosts: deploy_node
  become: yes
  become_user: "{{ ansible_user }}"
  tasks:

  - name: Replace TARGET_SYSTEM example.com with target_domain in offline_deploy_k8s
    lineinfile:
      path: /home/{{ ansible_user }}/wire-server-deploy/bin/wiab-demo/offline_deploy_k8s.sh
      regexp: '^TARGET_SYSTEM="example\.com"'
      line: 'TARGET_SYSTEM="{{ target_domain }}"'
      backrefs: yes

  - name: Replace CERT_MASTER_EMAIL example.com with target_domain in offline_deploy_k8s
    lineinfile:
      path: /home/{{ ansible_user }}/wire-server-deploy/bin/wiab-demo/offline_deploy_k8s.sh
      regexp: '^CERT_MASTER_EMAIL="certmaster@example\.com"'
      line: 'CERT_MASTER_EMAIL="certmaster@{{ target_domain }}"'
      backrefs: yes

  - name: Load WSD Docker image
    shell: |
      docker load -i "/home/{{ ansible_user }}/wire-server-deploy/containers-adminhost/container-wire-server-deploy.tgz" | awk '{print $3}'
    register: wsd_container

  - name: Process charts for demo environment
    shell: |
      {{ docker_cmd_base }} bash -c "source /wire-server-deploy/bin/wiab-demo/offline_deploy_k8s.sh && process_charts demo"
    args:
      executable: /bin/bash
    
  - name: Process values
    shell: |
      {{ docker_cmd_base }} bash -c "source /wire-server-deploy/bin/wiab-demo/offline_deploy_k8s.sh && process_values"
    args:
      executable: /bin/bash
    
  - name: Deploy cert manager
    shell: |
      {{ docker_cmd_base }} bash -c "source /wire-server-deploy/bin/wiab-demo/offline_deploy_k8s.sh && deploy_cert_manager"
    args:
      executable: /bin/bash
    
  - name: Deploy chart
    shell: |
      {{ docker_cmd_base }} bash -c "source /wire-server-deploy/bin/wiab-demo/offline_deploy_k8s.sh && deploy_charts {{ item }}"
    args:
      executable: /bin/bash
    loop: "{{ charts_to_deploy }}"

  - name: Deploy calling stack
    shell: |
      {{ docker_cmd_base }} bash -c "source /wire-server-deploy/bin/wiab-demo/offline_deploy_k8s.sh && deploy_calling_services"
    args:
      executable: /bin/bash
