- name: Package installation and configuration
  hosts: deploy_node
  become: yes
  tasks:
  - name: Install required packages
    block:
    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Install dependencies
      yum:
        name:
          - yq
          - jq
        state: present
        update_cache: yes

    - name: Add Docker repository to apt sources
      yum_repository:
        name: DockerCE
        description: "Repo for DockerCE"
        baseurl: "https://download.docker.com/linux/centos $(. /etc/os-release && echo $VERSION_CODENAME) stable"
        gpgcheck: no

    - name: Update apt package index
      yum:
        update_cache: yes

    - name: Install Docker packages
      yum:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        state: latest

    - name: Add rhel user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Reset SSH connection to apply docker group membership changes
      meta: reset_connection

    - name: Install Minikube
      get_url:
        url: "https://github.com/kubernetes/minikube/releases/download/{{ minikube_version }}/minikube-linux-amd64"
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Install kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ kubernetes_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
