- name: Check accessiblity of public IP
  hosts: deploy_node
  vars:
    test_port: 3478
  tasks:
  - name: Get public IP address
    uri:
      url: https://api.ipify.org
      return_content: yes
    register: public_ip_result
    failed_when: public_ip_result.status != 200
    retries: 3
    delay: 2
      
  - name: Store public IP and set facts
    set_fact:
      public_ip: "{{ public_ip_result.content | trim }}"
        
  - name: Display public IP address
    debug:
      msg: "Public IP address: {{ public_ip }}"

  - name: Create temporary listening port
    shell: |
      nc -k -l -p {{ test_port }} &
      echo $! > /tmp/nc_pid_{{ test_port }}
    async: 1
    poll: 0
    register: tcp_service
    ignore_errors: yes

  - name: Wait for listening service to start
    wait_for:
      port: "{{ test_port }}"
      state: started
      timeout: 5
      delay: 1
    ignore_errors: yes

  - name: Attempt to connect to the TCP service
    ansible.builtin.shell: |
      nc -zv -w 5 {{ public_ip }} {{ test_port }}
    register: connection_test
    ignore_errors: yes
    delegate_to: localhost

  - name: Display connection test result
    ansible.builtin.debug:
      msg: "{{ 'Public IP assigned to the node is reachable' if connection_test.rc == 0 else 'Connection test failed' }}"

  - name: Stop TCP service
    ansible.builtin.shell: |
      if [ -f /tmp/nc_pid_{{ test_port }} ]; then
        kill $(cat /tmp/nc_pid_{{ test_port }})
        rm -f /tmp/nc_pid_{{ test_port }}
      fi
    ignore_errors: yes

  - name: Set public IP for TURN service (if provided)
    ansible.builtin.set_fact:
      public_ip : "{{ coturn_public_ip | default('') }}"
    when: connection_test is failed

  - name: Check if alternative public IP is provided
    ansible.builtin.fail:
      msg: >
        Network connectivity test failed. Unable to reach port {{ test_port }} on the public IP ({{ public_ip }}).
        Please check your network configuration:
        1. Verify network routes and firewall rules
        2. Ensure TCP traffic to port {{ test_port }} is allowed on the public IP. Note: In case, iptables_rules playbook had run previously, clean them using clean_cluster -e remove_iptables=true
        3. If you're deploying in a private network environment, you must specify the 'coturn_public_ip' variable with the publicly accessible IP address for the TURN server.
    when: connection_test is failed and (coturn_public_ip is not defined or coturn_public_ip | length == 0)  
