ingress-nginx:
  controller:
    # There's no loadbalancer support in the Hetzner CI environment
    kind: DaemonSet
    service:
      type: NodePort
    image:
      tag: "v1.6.4"
      digest: ""
      digestChroot: ""
    admissionWebhooks:
      patch:
        image:
          tag: "v20220916-gd32f8c343"
          digest: ""
