- name: Install PostgreSQL packages
  import_playbook: postgresql-playbooks/postgres-install.yml

- name: Deploy PostgreSQL primary node
  import_playbook: postgresql-playbooks/postgres-deploy-primary.yml

- name: Deploy PostgreSQL replica nodes
  import_playbook: postgresql-playbooks/postgresql-replica-deploy.yml

- name: Verify PostgreSQL deployment
  import_playbook: postgresql-playbooks/postgres-verify.yml
